// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VkService.Data;

#nullable disable

namespace VkService.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230529161221_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3");

            modelBuilder.Entity("VkService.Data.Entities.VkMessage", b =>
                {
                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepostedFrom")
                        .HasColumnType("INTEGER");

                    b.HasKey("OwnerId", "Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("VkService.Data.Entities.VkUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VkService.Data.Entities.VkMessage", b =>
                {
                    b.OwnsOne("VkService.Data.Entities.VkMessageSearch", "Content", b1 =>
                        {
                            b1.Property<int>("OwnerId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.HasKey("OwnerId", "Id");

                            b1.ToTable("VkMessageSearch", (string)null);

                            b1.HasAnnotation("Sqlite:UseSqlReturningClause", false);

                            b1.WithOwner("Message")
                                .HasForeignKey("OwnerId", "Id");

                            b1.Navigation("Message");
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
